profiles:
  - name: "Dev"
    image: "fonalex45/aegis:dev"
    description: "Container for offensive security tools."
    options:
      host_networking: false
      default_mount: "./projects:/workspace"
  - name: "Main"
    image: "fonalex45/aegis:latest"
    description: "Container for offensive security tools."
    options:
      host_networking: true
      default_mount: "./projects:/workspace"


